
services:
  redis:
    image: redis:latest
    platform: linux/arm64
    command: redis-server --requirepass default
    environment:
      REDIS_USER: default
      REDIS_PASSWORD: default
    ports:
      - "6379:6379"

  n8n:
    image: n8nio/n8n:latest
    platform: linux/arm64
    environment:
      WEBHOOK_URL: http://host.docker.internal:5678
      N8N_HOST: host.docker.internal
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: debug
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
      N8N_SECURE_COOKIE: false
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    platform: linux/arm64
    volumes:
      - app_data:/app
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

volumes:
  n8n_data:
  app_data:
